In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\91993\Downloads\archive\Combined_dataset.csv")

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
df.shape

(1000, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [8]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [10]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [13]:
df=df.fillna("Not Available")

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:
df=df.drop_duplicates()

In [17]:
df[['title','final_price','rating']]

              title   final_price  rating
0       Lino Perros   "₹3,995.00"     3.8
1    Tommy Hilfiger   "₹2,899.00"     4.5
2             Lavie   "₹2,999.00"     4.4
3            F Gear   "₹1,675.00"     4.4
4         MYTRIDENT   "₹2,899.00"     4.7
..              ...           ...     ...
995           KREDO  "₹11,890.00"     3.5
996           GUESS   "₹8,900.00"     5.0
997        GIORDANO   "₹7,950.00"     2.8
998        Fastrack   "₹2,636.00"     4.3
999         BOLDFIT     "₹699.00"     3.8

[1000 rows x 3 columns]

In [18]:
df[df['rating']>4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,Not Available,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",Not Available,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Not Available,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",Not Available,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Not Available,Tru███m R███il,"[{""size"":""Onesize""}]",Not Available,Sho███o. ███-10█████████enu███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [21]:
df[['initial_price','final_price']].head()

   initial_price  final_price
0           3995  "₹3,995.00"
1           2899  "₹2,899.00"
2           2999  "₹2,999.00"
3           1675  "₹1,675.00"
4           2899  "₹2,899.00"

In [24]:
df['rating_score']=df['rating']*df['ratings_count']

In [25]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,rating_score
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,57.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,301.5
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,994.4
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,4628.8
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,56.4

In [27]:
df.to_csv('cleaned_dataset.csv',index=False)

In [28]:
print("Cleaned dataset saved sucessfully!")

Cleaned dataset saved sucessfully!