In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\91993\Downloads\archive (8)\Sample - Superstore.csv", encoding="latin1")

In [5]:
df.head

<bound method NDFrame.head of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1          2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
2          3  CA-2016-138688   6/12/2016   6/16/2016    Second Class
3          4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4          5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
9990    9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9991    9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9993    9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [6]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [7]:
df.shape

(9994, 21)

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [10]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [12]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

No missing values were found in the dataset, so no missing value handling was required.

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
technology = df[df["Category"] == "Technology"]
technology.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424,4,0.2,68.3568
19,20,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
26,27,CA-2016-121755,1/16/2016,1/20/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741
35,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737

In [16]:
df[["Customer Name", "Category", "Sales", "Quantity"]].head()

     Customer Name         Category     Sales  Quantity
0      Claire Gute        Furniture  261.9600         2
1      Claire Gute        Furniture  731.9400         3
2  Darrin Van Huff  Office Supplies   14.6200         2
3   Sean O'Donnell        Furniture  957.5775         5
4   Sean O'Donnell  Office Supplies   22.3680         2

In [17]:
df["Price"] = df["Sales"] / df["Quantity"]

In [18]:
df["Total_Amount"] = df["Price"] * df["Quantity"]

In [19]:
df[["Sales", "Quantity", "Price", "Total_Amount"]].head()

      Sales  Quantity     Price  Total_Amount
0  261.9600         2  130.9800      261.9600
1  731.9400         3  243.9800      731.9400
2   14.6200         2    7.3100       14.6200
3  957.5775         5  191.5155      957.5775
4   22.3680         2   11.1840       22.3680

In [20]:
df.to_csv("cleaned_superstore.csv", index=False)

In [21]:
import os

os.listdir()

['.3T',
 '.bash_history',
 '.cache',
 '.codex',
 '.copilot',
 '.eclipse',
 '.ghcp-appmod',
 '.ghcp-appmod-java',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.m2',
 '.matplotlib',
 '.npmrc',
 '.p2',
 '.packettracer',
 '.redhat',
 '.swt',
 '.vscode',
 '.vscode-shared',
 '11.java',
 '15.java',
 '2341004154',
 '3D Objects',
 'after operator',
 'AppData',
 'Application Data',
 'Array',
 'Assignment_1_data clean.ipynb',
 'bigelement',
 'bike.html',
 'Cisco Packet Tracer 9.0.0',
 'cleaned_dataset.csv',
 'cleaned_superstore.csv',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'drop.html',
 'eclipse',
 'EXAM',
 'Favorites',
 'form.html',
 'IdeaProjects',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'navbar.html',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TM.blf',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'output_parquet',
 'Postman',
 'PrintHood',
 'public class Main {.java',
 'pyt.py',
 'Recent',
 'return',
 'Saved Games',
 'scss.scss',
 'Searches',
 'SendTo',
 'Start Menu',
 'string',
 'style.css',
 'style1.css',
 'stylee.css',
 'Templates',
 'Untitled-1.html',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'Videos',
 'Week-6_Spark-Architecture.ipynb',
 'Week-7_Assignment.ipynb',
 'week5_assignment.py',
 'week5_Spark_Assignment.ipynb']

Week 7 Assignment Summary
Loaded the Superstore CSV dataset into a Pandas DataFrame.
Explored the dataset using head(), tail(), shape, columns, dtypes, and info().
Checked for missing values using isnull().sum() and found no missing values.
Checked for duplicate rows and found no duplicates.
Filtered the dataset for the Technology category.
Selected important columns for analysis.
Created the Price and Total_Amount derived columns.
Saved the cleaned dataset as cleaned_superstore.csv.

In [22]:
import os
os.listdir()

['.3T',
 '.bash_history',
 '.cache',
 '.codex',
 '.copilot',
 '.eclipse',
 '.ghcp-appmod',
 '.ghcp-appmod-java',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.m2',
 '.matplotlib',
 '.npmrc',
 '.p2',
 '.packettracer',
 '.redhat',
 '.swt',
 '.vscode',
 '.vscode-shared',
 '11.java',
 '15.java',
 '2341004154',
 '3D Objects',
 'after operator',
 'AppData',
 'Application Data',
 'Array',
 'Assignment_1_data clean.ipynb',
 'bigelement',
 'bike.html',
 'Cisco Packet Tracer 9.0.0',
 'cleaned_dataset.csv',
 'cleaned_superstore.csv',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'drop.html',
 'eclipse',
 'EXAM',
 'Favorites',
 'form.html',
 'IdeaProjects',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'navbar.html',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TM.blf',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{fa61414b-794b-11f1-a5aa-de5d64582373}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'output_parquet',
 'Postman',
 'PrintHood',
 'public class Main {.java',
 'pyt.py',
 'Recent',
 'return',
 'Saved Games',
 'scss.scss',
 'Searches',
 'SendTo',
 'Start Menu',
 'string',
 'style.css',
 'style1.css',
 'stylee.css',
 'Templates',
 'Untitled-1.html',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'Videos',
 'Week-6_Spark-Architecture.ipynb',
 'Week-7_Assignment.ipynb',
 'week5_assignment.py',
 'week5_Spark_Assignment.ipynb']